---------------------테이블 제거
DROP TABLE MEMBER cascade constraints;
DROP TABLE NOTICE cascade constraints;
DROP TABLE BUGREPORT cascade constraints;
DROP TABLE BUGREPORTANSWER cascade constraints;
DROP TABLE GALLERY_ADMIN cascade constraints;
DROP TABLE GALLERY_MEMBER cascade constraints;
DROP TABLE CALENDAR cascade constraints;
---------------------시퀀스 제거
DROP SEQUENCE notice_seq;
DROP SEQUENCE bug_seq;
DROP SEQUENCE mb_gallery_seq;
DROP SEQUENCE ad_gallery_seq;
---------------------시퀀스 생성
CREATE SEQUENCE notice_seq
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

CREATE SEQUENCE bug_seq
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

CREATE SEQUENCE ad_gallery_seq
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

CREATE SEQUENCE mb_gallery_seq
       INCREMENT BY 1
       START WITH 1
       MINVALUE 1
       MAXVALUE 9999
       NOCYCLE
       NOCACHE
       NOORDER;

CREATE TABLE MEMBER (
	USERID 	            varchar2(20)		        NOT NULL,
	USERPASSWORD	varchar2(100)		        NOT NULL,
	USEREMAIL	        varchar2(100)		        NOT NULL,
	USERNAME	        varchar2(30)		        NOT NULL,
	USERGENDER	    varchar2(1)		            NOT NULL,
	USERADMIN	    char(1)	DEFAULT 'N'	NOT NULL,
	USERLOGINOK	    char(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."USERID" IS '유저아이디';
COMMENT ON COLUMN "MEMBER"."USERPASSWORD" IS '비밀번호';
COMMENT ON COLUMN "MEMBER"."USEREMAIL" IS '이메일';
COMMENT ON COLUMN "MEMBER"."USERNAME" IS '유저이름';
COMMENT ON COLUMN "MEMBER"."USERGENDER" IS '성별';
COMMENT ON COLUMN "MEMBER"."USERADMIN" IS '관리자여부';
COMMENT ON COLUMN "MEMBER"."USERLOGINOK" IS '로그인가능여부';


CREATE TABLE NOTICE (
	NOTICE_NO	            number      	NOT NULL,
	USERID                  varchar2(20)		NOT NULL,
	NOTICE_TITLE	        varchar2(100)		NOT NULL,
	NOTICE_DATE	        date	DEFAULT sysdate	NOT NULL,
	NOTICE_CONTENT	varchar2(2000)		NOT NULL,
	NOTICE_READCOUNT	number	DEFAULT 1	NOT NULL,
	NOTICE_UPFILE	        varchar2(100)		NULL,
	NOTICE_REFILE	        varchar2(100)		NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '공지번호';
COMMENT ON COLUMN "NOTICE"."USERID" IS '유저아이디';
COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '공지제목';
COMMENT ON COLUMN "NOTICE"."NOTICE_DATE" IS '등록날짜';
COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '공지내용';
COMMENT ON COLUMN "NOTICE"."NOTICE_READCOUNT" IS '조회수';
COMMENT ON COLUMN "NOTICE"."NOTICE_UPFILE" IS '첨부파일';
COMMENT ON COLUMN "NOTICE"."NOTICE_REFILE" IS '첨부파일수정';

CREATE TABLE BUGREPORT (
	BUG_NO	        number NOT NULL,
	USERID	        varchar2(20)		NOT NULL,
	BUG_TITLE	    varchar2(100)		NOT NULL,
	BUG_DATE	    date	DEFAULT sysdate	NOT NULL,
	BUG_CONTENT	varchar2(2000)		NOT NULL,
	BUG_READCOUNT	number	DEFAULT 1	NOT NULL,
	BUG_UPFILE	    varchar2(100)		NULL,
	BUG_REFILE	    varchar2(100)		NULL
);

COMMENT ON COLUMN "BUGREPORT"."BUG_NO" IS '글 번호';
COMMENT ON COLUMN "BUGREPORT"."USERID" IS '유저아이디';
COMMENT ON COLUMN "BUGREPORT"."BUG_TITLE" IS '글 제목';
COMMENT ON COLUMN "BUGREPORT"."BUG_DATE" IS '등록날짜';
COMMENT ON COLUMN "BUGREPORT"."BUG_CONTENT" IS '글 내용';
COMMENT ON COLUMN "BUGREPORT"."BUG_READCOUNT" IS '조회수';
COMMENT ON COLUMN "BUGREPORT"."BUG_UPFILE" IS '첨부파일';
COMMENT ON COLUMN "BUGREPORT"."BUG_REFILE" IS '첨부파일수정';

CREATE TABLE BUGREPORTANSWER  (
	BUG_ANUM	number	DEFAULT 1	NOT NULL,
	BUG_NO	number	NOT NULL,
	USERID 	varchar2(20)		NOT NULL,
	BUG_ADATE	date	DEFAULT sysdate	NOT NULL,
	BUG_ANSWER	varchar2(200)		NOT NULL
);

COMMENT ON COLUMN "BUGREPORTANSWER"."BUG_ANUM" IS '댓글번호';
COMMENT ON COLUMN "BUGREPORTANSWER"."BUG_NO" IS '글 번호';
COMMENT ON COLUMN "BUGREPORTANSWER"."USERID" IS '유저아이디';
COMMENT ON COLUMN "BUGREPORTANSWER"."BUG_ADATE" IS '답변날짜';
COMMENT ON COLUMN "BUGREPORTANSWER"."BUG_ANSWER" IS '답글내용';

CREATE TABLE GALLERY_ADMIN(
	SNUM	number	NOT NULL,
	USERID	varchar2(20)		NOT NULL,
	AD_SNAME	varchar2(30)		NULL
);

COMMENT ON COLUMN "GALLERY_ADMIN"."SNUM" IS '스티커등록번호';
COMMENT ON COLUMN "GALLERY_ADMIN"."USERID" IS '유저아이디';
COMMENT ON COLUMN "GALLERY_ADMIN"."AD_SNAME" IS '스티커이름';

CREATE TABLE GALLERY_MEMBER (
    USER_SNUM            number             NOT NULL,
	SNUM	                number          	NULL,
	USERID	                varchar2(20)		NOT NULL,
    MB_IMGNAME      	varchar2(100)		NULL,
	MB_SNAME	            varchar2(30)		NULL,
    MB_IMAGE_DATE	    date	DEFAULT sysdate	NOT NULL,
    CATEGORY             varchar2(4)          NULL
);

COMMENT ON COLUMN "GALLERY_MEMBER"."USER_SNUM" IS '유저스티커등록번호';
COMMENT ON COLUMN "GALLERY_MEMBER"."MB_IMGNAME" IS '이미지 이름';
COMMENT ON COLUMN "GALLERY_MEMBER"."SNUM" IS '스티커등록번호';
COMMENT ON COLUMN "GALLERY_MEMBER"."USERID" IS '유저아이디';
COMMENT ON COLUMN "GALLERY_MEMBER"."MB_SNAME" IS '스티커이름';
COMMENT ON COLUMN "GALLERY_MEMBER"."MB_IMAGE_DATE" IS '이미지등록날짜';
COMMENT ON COLUMN "GALLERY_MEMBER"."CATEGORY" IS '이미지분류';


CREATE TABLE CALENDAR (
	CALENDAR_DATE   	date		NOT NULL,
	USERID	                varchar2(20)		NOT NULL,
	USER_SNUM      	number		NULL,
	CALENDAR_CONTENT	varchar2(100)		NOT NULL
);

COMMENT ON COLUMN "CALENDAR"."CALENDAR_DATE" IS '등록날짜';
COMMENT ON COLUMN "CALENDAR"."USERID" IS '유저아이디';
COMMENT ON COLUMN "CALENDAR"."USER_SNUM" IS '유저 스티커 등록번호';
COMMENT ON COLUMN "CALENDAR"."CALENDAR_CONTENT" IS '캘린더 내용';

-------------------------PK 설정
ALTER TABLE MEMBER ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("USERID");
ALTER TABLE NOTICE ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("NOTICE_NO");
ALTER TABLE BUGREPORT ADD CONSTRAINT "PK_BUGREPORT" PRIMARY KEY ("BUG_NO");
ALTER TABLE BUGREPORTANSWER ADD CONSTRAINT "PK_BUGREPORTANSWER" PRIMARY KEY ("BUG_ANUM");
ALTER TABLE GALLERY_ADMIN ADD CONSTRAINT "PK_GALLERY_ADMIN" PRIMARY KEY ("SNUM");
ALTER TABLE GALLERY_MEMBER ADD CONSTRAINT "PK_CALLERY_MEMBER" PRIMARY KEY ("USER_SNUM");
ALTER TABLE CALENDAR ADD CONSTRAINT "PK_CALENDAR" PRIMARY KEY ("CALENDAR_DATE");
-------------------------FK 설정
ALTER TABLE NOTICE ADD CONSTRAINT "FK_MEMBER_TO_NOTICE_1" FOREIGN KEY ("USERID")
REFERENCES MEMBER (	"USERID");
ALTER TABLE BUGREPORT ADD CONSTRAINT "FK_MEMBER_TO_BUGREPORT_1" FOREIGN KEY ("USERID")
REFERENCES MEMBER ("USERID");
ALTER TABLE BUGREPORTANSWER ADD CONSTRAINT "FK_BUGREPORT_TO_BUGREPORTANSWER_1" FOREIGN KEY ("BUG_NO")
REFERENCES BUGREPORT ("BUG_NO");
ALTER TABLE BUGREPORTANSWER ADD CONSTRAINT "FK_MEMBER_TO_BUGREPORTANSWER_1" FOREIGN KEY ("USERID")
REFERENCES MEMBER ("USERID");
ALTER TABLE GALLERY_ADMIN ADD CONSTRAINT "FK_MEMBER_TO_GALLERY_ADMIN_1" FOREIGN KEY ("USERID")
REFERENCES MEMBER ("USERID");
ALTER TABLE GALLERY_MEMBER ADD CONSTRAINT "FK_GALLERY_ADMIN_TO_CALLERY_MEMBER_1" FOREIGN KEY ("SNUM")
REFERENCES GALLERY_ADMIN ("SNUM");
ALTER TABLE GALLERY_MEMBER ADD CONSTRAINT "FK_MEMBER_TO_CALLERY_MEMBER_1" FOREIGN KEY ("USERID")
REFERENCES MEMBER ("USERID");
ALTER TABLE CALENDAR ADD CONSTRAINT "FK_MEMBER_TO_CALENDAR_1" FOREIGN KEY ("USERID")
REFERENCES MEMBER (	"USERID");
ALTER TABLE CALENDAR ADD CONSTRAINT "FK_CALLERY_MEMBER_TO_CALENDAR_1" FOREIGN KEY ("USER_SNUM")
REFERENCES GALLERY_MEMBER ("USER_SNUM");

-------------------------------check 조건
ALTER TABLE MEMBER
ADD CONSTRAINT CHK_MEM_LOK CHECK (USERLOGINOK IN ('Y', 'N'));
ALTER TABLE GALLERY_MEMBER
ADD CONSTRAINT CHK_CATEGORY_NAME CHECK (CATEGORY IN ('ear', 'nose'));

---------------------------------------admin 관리자 등록
INSERT INTO MEMBER VALUES ('admin','admin','admin@test.org','관리자','M','Y','Y');

---------------------------------------일반 유저 2명 등록
INSERT INTO MEMBER
VALUES ('user01','user01','user01@test.org','일반유저','F','N','Y');
INSERT INTO MEMBER
VALUES ('user02','user02','user02@test.org','일반유저','M','N','Y');

---------------------------------------공지글 2개 등록
INSERT INTO NOTICE VALUES (notice_seq.nextval, 'admin','공지1번',sysdate,'첫번째 공지글입니다.',default,default,default);

INSERT INTO "NOTICE" VALUES (notice_seq.nextval, 'admin','공지2번',sysdate,'두번째 공지글입니다.',default,default,default);

---------------------------------------버그리포트 2개 등록
INSERT INTO "BUGREPORT" VALUES (bug_seq.nextval, 'user01','문제있어요',sysdate,'문제가있네요',default,default,default);
INSERT INTO "BUGREPORT" VALUES (bug_seq.nextval, 'user02','문제없어요',sysdate,'문제가없어요',default,default,default);

---------------------------------------버그리포트 답변 등록(1개만)
INSERT INTO "BUGREPORTANSWER" VALUES (default,1,'admin',sysdate,'네네');

---------------------------------------갤러리 관리자 스티커 등록
INSERT INTO GALLERY_ADMIN VALUES(ad_gallery_seq.nextval,'admin',null);
---------------------------------------갤러리 멤버 스티커 등록
INSERT INTO GALLERY_MEMBER VALUES (mb_gallery_seq.nextval,1, 'admin', 'img-1.jpg', 'sticker-1.png', sysdate,'ear');

commit;
